### ISSUE TITLE
Readings not showing in html/flask app

### ISSUE THREAD

**Issue by Sanchit-chitke** [hrishi-2407/VisionMetrics#1]
**Problem in variable naming which is causing the problem,** 
```
@app.route('/')
def index():
    **reading** = take_measure(threshold_img, threshold_ln, minLineLength, maxLineGap,
                           diff1LowerBound, diff1UpperBound, diff2LowerBound, diff2UpperBound,
                           min_angle, max_angle, min_value, max_value, units)
    return render_template('index.html', reading=reading)
```

declaring variable  **reading** in flask route and accessing readings in html
```
 <ul>
            {% for reading in readings %}
                <li>{{ reading }}</li> <!-- Display each reading dynamically -->
            {% endfor %}
        </ul>
```

### Modify the Flask route to pass readings to the template
```
@app.route('/')
def index():
    readings = take_measure(threshold_img, threshold_ln, minLineLength, maxLineGap,
                            diff1LowerBound, diff1UpperBound, diff2LowerBound, diff2UpperBound,
                            min_angle, max_angle, min_value, max_value, units)
    return render_template('index.html', readings=readings)
<hr>
```

```
<div>
    <h2>Readings:</h2>
    <ul>
        {% for reading in readings %}
            <li>{{ reading }}</li> <!-- Display each reading dynamically -->
        {% endfor %}
    </ul>
</div>
```
This changes shold solve the problem.

**Comment by hrishi-2407** [comment]
Thanks for your insights. I completely overlooked it. 
But this time, after making the changes and running the code, the web interface blacked out. However, it was capturing the live video feed and printing the readings in the ide's terminal.

This might be due to the take_measure() function running in an infinite loop to continuously capture video frames and process them. As a result, the Flask routes that call this function ('/' and '/video_feed') are not being executed.

To address this, I'm trying to move the video processing code into a separate thread or process so that it can run independently of the Flask application.
